#Configuration for WebClient without LoadBalanced
#service:
#  client:
#    uri: http://localhost:8081/api/v1/client
#  account:
#    uri: http://localhost:8082/api/v1/account
#  credit:
#    uri: http://localhost:8083/api/v1/credit
